import Head from "next/head";
import { useEffect } from "react";
import cookieCutter from "cookie-cutter";

export default function Home() {
  useEffect(() => {
    const token = cookieCutter.get("token") || null;
    if (!token) window.location.href = "/seller/login";
    else window.location.href = "/seller/dashboard";
  }, []);
  return (
    <div>
      <Head>
        <title>Seller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
